#version: "3.8"

services:
  # minio:
  #   image: minio/minio
  #   command: server /data/minio --console-address ":9001"
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin
  #     - MINIO_ROOT_PASSWORD=minioadmin
  #   networks:
  #     - minio-local
  db:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: postgresadmin
      POSTGRES_DB: Meta
    ports:
      - 5432:5432
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - minio-local
  server:
    container_name: server
    build: .
    networks:
      - minio-local
    env_file: 
      - .env
    environment:
      - NPGSQL_DISABLE_GSSAPI=true
    # ports:
    #   - 8080:8080
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./nginx_logs:/var/log/nginx
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - mode: host
        protocol: tcp
        published: 8080
        target: 8080
    depends_on:
      - server
    networks:
      - minio-local
    env_file: 
      - .env
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - MINIO_HOST
      - MINIO_PORT


networks:
  minio-local:
    driver: bridge